// import "../styles/globals.css";
import "react-toastify/dist/ReactToastify.css";

import { WagmiProvider } from "wagmi";
import config from "../components/config";

function MyApp({ children }) {
  // const { locale } = useRouter();

  return (
    <html>
      <WagmiProvider config={config}>
        <body>{children}</body>
      </WagmiProvider>
    </html>
  );
}

export default MyApp;
// These styles apply to every route in the application
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
